name: CI/CD para Front-End na EC2 pública

on:
  push:
    branches:
      - main # O branch que acionará o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # 2. Configuração do ambiente Node
      - name: FE - Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          
      # 3. Build da aplicação (Se for uma aplicação que precisa ser construída, ex: React, Angular, Vue)
      - name: FE - Instalar Dependências e Fazer Build
        run: |
             npm install
             npm run build --if-present 
             # Se sua app não precisar de build, remova esta etapa
        working-directory: ./front-end

      # 4. Deploy (Transferência de arquivos e execução de comandos remotos)
      - name: FE - Copiar arquivos e Deploy (Usando SSH com rsync)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/frontend
          # ARGS para rsync: -rltgoDzvO para cópia recursiva, compressão e outros
          ARGS: "-rltgoDzvO --delete" 
          # SOURCE: O que será copiado. Pode ser o diretório de build (ex: ./dist)
          SOURCE: "./front-end/dist/" 

