name: CI/CD para Front-End na EC2 pública

on:
  push:
    branches:
      - main # O branch que acionará o deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # 2. Configuração do ambiente Node
      - name: FE - Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          
      # 3. Build da aplicação (Se for uma aplicação que precisa ser construída, ex: React, Angular, Vue)
      - name: FE - Instalar Dependências e Fazer Build
        run: |
             npm install
             npm run build --if-present 
             # Se sua app não precisar de build, remova esta etapa
        working-directory: ./front-end

      # 4. Deploy para Web1
      - name: FE - Deploy para Web1
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.WEB1_HOST }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/frontend
          ARGS: "-rltgoDzvO --delete" 
          SOURCE: "./front-end/dist/"

      # 5. Deploy para Web2
      - name: FE - Deploy para Web2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.WEB1_HOST }}
          REMOTE_HOST: ${{ secrets.WEB2_HOST }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/frontend
          ARGS: "-rltgoDzvO --delete" 
          SOURCE: "./front-end/dist/"

      # 6. Reiniciar NGINX na Web1
      - name: Reiniciar NGINX na Web1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEB1_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker compose -f /home/ubuntu/compose.yaml restart

      # 7. Reiniciar NGINX na Web2
      - name: Reiniciar NGINX na Web2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEB2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker compose -f /home/ubuntu/compose.yaml restart 

